import { escapeHtml } from './entities.mjs';

const classes = [
  { name: 'Lord Knight', sprite: 'lord-knight.gif', roles: ['STR'], identity: 'Two-handed-sword STR bruiser. Bowling Bash carries you through second job; after transcending, Spiral Pierce adds a spear-based signature hit.', grabs: 'Zweihander[1] (Bowling Bash +140%), Hydra Card (Bowling Bash +15%), Worm Tail Card (Spiral Pierce +18%).', essence: 'Lord Knight Essence → Essence II (Hunter’s Guild shop, 60 / 150 Hunter Coins): +STR and both signatures +35%.', next: 'Monster Hunter offers Lord Knight’s Warbreaker for Bowling Bash and Ravenspine for Spiral Pierce.' },
  { name: 'Paladin', sprite: 'paladin.gif', roles: ['VIT'], identity: 'VIT shield tank whose Shield Chain, Grand Cross, and Pressure scale together. Keep a shield equipped.', grabs: 'Buckler[1] (Shield Boomerang +80%), Haedonggum (Grand Cross +50%), Yoyo Card (Shield Chain +18%).', essence: 'Paladin Essence → Essence II: +VIT and all three signatures +35%.', next: 'Monster Hunter offers Crusader’s Juggernaut Wall (Shield Boomerang +150%).' },
  { name: 'High Priest', sprite: 'priest.gif', roles: ['INT', 'Support'], identity: 'The support backbone with real holy damage. Magnus Exorcismus and Holy Light excel against Undead and Demon packs.', grabs: 'Rosary[1] (Magnus Exorcismus +60%, Holy Light +100%), Mace[1] (Magnus Exorcismus +50%), Mummy Card (Magnus Exorcismus +15%).', essence: 'High Priest Essence → Essence II: +INT and both signatures +35%.', next: 'The Build Librarian explains the full Priest Zealot Support combo.' },
  { name: 'High Wizard', sprite: 'high-wizard.gif', roles: ['INT'], identity: 'INT glass cannon. Meteor Storm, Napalm Vulcan, and Jupitel Thunder add trans-tier burst to the classic bolt and Storm Gust kit.', grabs: 'Circlet[1] (Storm Gust, Lord of Vermilion, and Jupitel Thunder +50%), Glasses[1] (Napalm Vulcan +60%), Pasana Card (Meteor Storm +15%).', essence: 'High Wizard Essence → Essence II: +INT and all three signatures +35%.', next: 'The Build Librarian can check the Circlet and Glasses combo.' },
  { name: 'Whitesmith', sprite: 'whitesmith.gif', roles: ['STR'], identity: 'STR cart-smith. Cart Termination hammers one target while Cart Revolution clears packs; both expect a parked, loaded cart.', grabs: 'Axe[1] (Cart Termination +120%), Belt (Cart Revolution +100%, Mammonite +40%), Goblin Card (Cart Termination +15%).', essence: 'Whitesmith Essence → Essence II: +STR, Cart Termination +40%, Cart Revolution +35%.', next: 'The Build Librarian documents the Merchant Brawler combo.' },
  { name: 'Creator', sprite: 'creator.gif', roles: ['INT', 'DEX'], identity: 'INT/DEX bomber. Acid Demonstration is the burst tool; Acid Terror and Demonstration are everyday throws.', grabs: 'Cutlus or Smasher[1] (Demonstration and Acid Terror), Celebrant’s Mitten (Acid Demonstration +60%), Scorpion Card (all three +12–15%).', essence: 'Creator Essence → Essence II: +INT/+DEX, Acid Demonstration +40%, Acid Terror and Demonstration +35%.', next: 'Both weapons are sold at the Fun Gear Armory for an immediate start.' },
  { name: 'Sniper', sprite: 'sniper.gif', roles: ['DEX'], identity: 'DEX archer. Double Strafe is the leveling workhorse; Sharp Shooting and Falcon Assault become the trans burst routes.', grabs: 'Gakkung Bow (Charge Arrow +75%, Sharp Shooting +50%), CrossBow[1] (Arrow Shower +100%), Wild Rose Card (Sharp Shooting +12%).', essence: 'Sniper Essence → Essence II: +DEX and Double Strafe, Sharp Shooting, and Falcon Assault +35%.', next: 'Monster Hunter offers Falcon’s Wing (Falcon Assault +70%).' },
  { name: 'Assassin Cross', sprite: 'assassin-cross.gif', roles: ['AGI'], identity: 'AGI/Flee crit-crasher. Sonic Blow opens; Soul Breaker and Venom Splasher round out the trans kit.', grabs: 'Tsurugi[1] (Soul Breaker +100%), Jur[1] (Grimtooth +80%), Orc Warrior Card (Sonic Blow +12%).', essence: 'Assassin Cross Essence → Essence II: +AGI, +5 Flee, Sonic Blow and Soul Breaker +35%, Venom Splasher +40%.', next: 'The Build Librarian explains the Assassin Bomber Brooch combo.' },
  { name: 'Champion', sprite: 'champion.gif', roles: ['STR', 'DEX'], identity: 'STR/DEX fist fighter. Chain Crush Combo leads into Asura Strike, Finger Offensive, and Palm Strike after transcending.', grabs: 'Fist[1] (Finger Offensive +80%, Asura Strike +50%), Chain[1] (Chain Crush Combo +120%), Matyr Card (Palm Strike +15%).', essence: 'Champion Essence → Essence II: +STR and all three signatures +35%.', next: 'The Build Librarian covers the Biretta[1] Finger Offensive and Chain Combo route.' },
  { name: 'Professor', sprite: 'professor.gif', roles: ['INT', 'Support'], identity: 'INT caster/support hybrid. Soul Burn is the signature punish; Soul Strike and Fire Ball remain reliable damage.', grabs: 'Wand[1] (Fire Ball +100%), Rod[1] (Soul Strike +100%), Ghostring Card (Soul Strike and Soul Burn +15%).', essence: 'Professor Essence → Essence II: +INT and Soul Burn, Soul Strike, and Fire Ball +35%.', next: 'The Build Librarian documents the Battle Mage Grimoire combo.' },
  { name: 'Stalker', sprite: 'stalker.gif', roles: ['AGI'], identity: 'Adaptive AGI rogue. Back Stab opens from stealth and Sightless Mind becomes the trans finisher.', grabs: 'Gladius (Back Stab +100%, Intimidate +80%), Rogue’s Treasure (Sightless Mind +50%), Pest Card (Sightless Mind +15%).', essence: 'Stalker Essence → Essence II: +AGI and Back Stab and Sightless Mind +35%.', next: 'The Build Librarian checks the Shadow Skirmisher’s Toolkit combo.' },
  { name: 'Clown', sprite: 'clown-gypsy.gif', roles: ['DEX'], identity: 'DEX bard-archer hybrid. Arrow Vulcan is shared with Gypsy; Musical Strike is the solo staple.', grabs: 'Lute[1] (Musical Strike +100%), Jakk Card (Arrow Vulcan +12%), Requiem Card (Musical Strike +15%).', essence: 'Clown Essence → Essence II: +DEX and Arrow Vulcan and Musical Strike +35%.', next: 'Monster Hunter offers Vulcan’s Fanfare (Arrow Vulcan +110%).' },
  { name: 'Gypsy', sprite: 'dancer-gypsy.gif', roles: ['DEX'], identity: 'DEX dancer-archer hybrid. Arrow Vulcan is shared with Clown; Slinging Arrow is the solo staple.', grabs: 'Rope[1] (Slinging Arrow +100%), Jakk Card (Arrow Vulcan +12%), Toad Card (Slinging Arrow +15%).', essence: 'Gypsy Essence → Essence II: +DEX and Arrow Vulcan and Slinging Arrow +35%.', next: 'Monster Hunter offers Vulcan’s Refrain (Arrow Vulcan +110%).' },
  { name: 'Soul Linker', sprite: 'soul-linker.gif', roles: ['INT', 'Support'], identity: 'INT support/utility. Esma, Estin, and Estun cover offense; Spirit Links make the party stronger.', grabs: 'Deviruchi Card (Esma +15%), Munak Card (Estin +15%), Dokebi Card (Estun +15%).', essence: 'Soul Linker Essence → Essence II: +INT and all three +35%; the thin gear pool makes this a particularly valuable jump.', next: 'Recruit a friend or use @allies—the class earns its keep supporting a party.' },
];

export function renderClasses() {
  const page = document.createElement('section');
  page.className = 'wiki-page editorial-page';
  page.innerHTML = `<header class="wiki-masthead editorial-masthead"><div class="container"><p class="eyebrow">Episode 13 · Transcendent second jobs</p><h1>Find the fantasy that fits you</h1><p>Fourteen complete early-game plans from the in-game Class Advisor: what to grab cheaply, what to save Hunter Coins for, and where to go once geared.</p></div></header><div class="container class-guide-grid">${classes.map(playerClass => `<article><div class="class-guide-sprite"><img src="assets/classes/${playerClass.sprite}" alt="" loading="lazy"></div><div><p class="eyebrow">${playerClass.roles.map(escapeHtml).join(' · ')}</p><h2>${escapeHtml(playerClass.name)}</h2><p>${escapeHtml(playerClass.identity)}</p><details><summary>Progression plan</summary><p><strong>Best early grabs:</strong> ${escapeHtml(playerClass.grabs)}</p><p><strong>Save up for:</strong> ${escapeHtml(playerClass.essence)}</p><p><strong>Once you’re geared:</strong> ${escapeHtml(playerClass.next)}</p></details><p><a href="#builds">Explore ${escapeHtml(playerClass.name)} builds →</a></p></div></article>`).join('')}</div>`;
  return page;
}
