import { escapeHtml } from './entities.mjs';

const instances = [
  { slug: 'amdarais', name: 'Old Glast Heim — Amdarais', type: 'Flagship raid', level: 99, hp: 7500000, entry: 'Hugin · Eden HQ entrance hall', cadence: '1/day · VIP +1', npc: '4_M_SAGE_C.gif', why: 'A full story raid through three besieged sectors, the Root of Corruption, twin commanders, and Amdarais.', rewards: 'Temporal Boots crafting materials and the grail-tier Amdarais Card.', steps: ['Rescue the west chapel and clear the east refinery.', 'Break the north courtyard garrison and defeat the Root of Corruption.', 'Clear both second-floor wings and their Commanders of Destruction.', 'Manage Amdarais’s healing reinforcement waves and use Varmundt’s Ghost stations.'] },
  { slug: 'ferlock', name: 'Assault on the Airship — Captain Ferlock', type: 'Flagship raid', level: 99, hp: 6500000, entry: 'Sky Warden · Eden HQ entrance hall', cadence: '1/day · VIP +1', npc: '4_M_JOB_KNIGHT1.gif', why: 'A two-deck defense of Ferlock’s airship, from the upper deck through the engine room and back.', rewards: 'A choice of three build-focused capes plus the universal Ferlock Card.', steps: ['Hold the top deck against Rotar Zairo, Beholders, Gremlins, and Acidus.', 'Descend to the damaged engine room and clear two more waves.', 'Defeat the Wyvern gatekeeper and return to Captain Ferlock.', 'Kill Sky Sentinels quickly to stop his healing and dodge the 40% HP fire-breath telegraph.'] },
  { slug: 'ghostpalace', name: 'Ghost Palace — Reliquary Warden', type: 'Flagship raid', level: 99, hp: 8500000, entry: 'Palace Keeper · Eden HQ entrance hall', cadence: '1/day · VIP +1', npc: '4_F_VALKYRIE.gif', why: 'Sakray’s five-floor tragedy followed by an optional true final boss after the story closes.', rewards: 'Gray Shards for a 14-weapon line, armor set, and Knight Sakray Card.', steps: ['Fight through five floors of the royal family’s tragedy.', 'Defeat the Torturous Redeemer mid-boss and finish Sakray’s story.', 'Choose whether to leave with the clear reward or challenge the Reliquary Warden.', 'Break its Ward by killing both Anchor Wisps and stop reinforcement healing.'] },
  { slug: 'bakonawa', name: 'Bakonawa Lake', type: 'Malaya hunt', level: 92, hp: 2900000, entry: 'Taho · Eden HQ entrance hall', cadence: '24-hour cooldown', npc: '4_M_OILMAN.gif', why: 'A three-phase ritual fight against a moon-eating dragon.', rewards: 'Guaranteed Ancient Grudge, a Bakonawa Card chance, and a rare zeny jackpot.', steps: ['Bring Bakonawa low before the first ten-minute timer.', 'When he dives, destroy two Caldrons and two Gongs within five minutes.', 'Defeat Enraged Bakonawa while the Wakwak swarm grows.'] },
  { slug: 'bangungot', name: 'Bangungot Hospital', type: 'Malaya hunt', level: 93, hp: 2500000, entry: 'Nurse Maenne · Eden HQ entrance hall', cadence: '24-hour cooldown', npc: '1_F_04.gif', why: 'Six haunted wards lead to a heal-race against Bangungot’s own spirit.', rewards: 'Ancient Grudge, Bangungot Boots of Nightmare, Kalasag, and the Bangungot Card.', steps: ['Clear six wards of undead and enter the boss room.', 'Follow the shifting warp tiles when Bangungot retreats.', 'Destroy the Pillar of Spirit within about thirty seconds before it heals him to full.'] },
  { slug: 'buwaya', name: 'Buwaya Cave', type: 'Malaya hunt', level: 99, hp: 2500000, entry: 'Buwaya Cave Warden · Eden HQ entrance hall', cadence: '23-hour cooldown', npc: '4_M_JOB_KNIGHT1.gif', why: 'A crocodile-god hunt built around hit-count armor and decoys.', rewards: 'Ancient Grudge, Buwaya Sack Cloth, Kalasag, and the Buwaya Card.', steps: ['Break both exposed Weakness points with twenty hits each.', 'Use the opening to speak with captives for a buff.', 'Ignore the decoys and bring down the original Buwaya.'] },
];

export function renderInstances(slug = null) {
  const selected = slug ? instances.find(instance => instance.slug === slug) : null;
  if (selected) return renderInstance(selected);
  const page = document.createElement('section');
  page.className = 'wiki-page editorial-page';
  page.innerHTML = `<header class="wiki-masthead editorial-masthead"><div class="container"><p class="eyebrow">Endgame adventures</p><h1>Instances with a story to tell</h1><p>Three staged flagship raids and three shorter Malaya hunts. Learn the entry requirements, encounter flow, and reason to return.</p></div></header><div class="container instance-grid">${instances.map(instance => `<a href="#instance/${instance.slug}"><span class="instance-npc"><img src="assets/npcs/${instance.npc}" alt="" loading="lazy"></span><p class="eyebrow">${instance.type}</p><h2>${escapeHtml(instance.name)}</h2><p>${escapeHtml(instance.why)}</p><dl><div><dt>Level</dt><dd>${instance.level}+</dd></div><div><dt>Boss HP</dt><dd>${(instance.hp / 1000000).toFixed(1)}M</dd></div><div><dt>Entry</dt><dd>${instance.cadence}</dd></div></dl><strong>View walkthrough →</strong></a>`).join('')}</div>`;
  return page;
}

function renderInstance(instance) {
  const page = document.createElement('section');
  page.className = 'wiki-page editorial-page instance-detail-page';
  page.innerHTML = `<header class="wiki-masthead instance-masthead"><div class="container"><a class="back-link" href="#instances">← All instances</a><p class="eyebrow">${instance.type}</p><h1>${escapeHtml(instance.name)}</h1><p>${escapeHtml(instance.why)}</p><dl class="instance-facts"><div><dt>Required level</dt><dd>${instance.level}+</dd></div><div><dt>Boss HP</dt><dd>${instance.hp.toLocaleString()}</dd></div><div><dt>Availability</dt><dd>${instance.cadence}</dd></div></dl></div></header><div class="container instance-article"><aside><img src="assets/npcs/${instance.npc}" alt="" loading="lazy"><p class="eyebrow">Entry NPC</p><h2>${escapeHtml(instance.entry.split(' · ')[0])}</h2><p>${escapeHtml(instance.entry.split(' · ')[1])}</p></aside><article><section><p class="eyebrow">Walkthrough</p><h2>How the encounter unfolds</h2><ol class="walkthrough">${instance.steps.map((step, index) => `<li><span>${String(index + 1).padStart(2, '0')}</span><p>${escapeHtml(step)}</p></li>`).join('')}</ol></section><section class="reward-callout"><p class="eyebrow">Why farm it</p><h2>The reward chase</h2><p>${escapeHtml(instance.rewards)}</p><p>Flagship rewards scale with Challenge Tier; item and card drop rates do not. Cards remain at the server’s fixed 1× rate.</p></section></article></div>`;
  return page;
}
